<?php
//test
$start=microtime();
$start=explode(" ",$start);
$start=$start[1]+$start[0];

//sleep(2);//halt the script for 2 seconds
//I put this just to affect the final page process time output...u will have your code here..

//record the ending time
$end=microtime();
$end=explode(" ",$end);
$end=$end[1]+$end[0]; 
include("konek.php");
$q=mysqli_query($mysqli,"select id_j,jabatan from jabatan where Tahun=2011  order by id_j");

while($data=mysqli_fetch_array($q))
{
		
	$q1=mysqli_query($mysqli,"Select count(*) from sk where id_j=$data[0]");
	$cek=mysqli_fetch_array($q1);
		
	if($cek[0]==0)
	echo("$data[1]<br>");
	
	
}
//record the ending time
$end=microtime();
$end=explode(" ",$end);
$end=$end[1]+$end[0]; 
printf("Page was generated by PHP %s in %f seconds",phpversion(),$end-$start);

?>